import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
    providedIn: 'root'
})

// Eventually this will call a http service to populate the institution control
// for now , using static data
export class InstitutionService {

    institutions = [
        { label: 'Academy of Learning - Airdrie', value: 6944, city: 'Airdrie', province: 'Alberta', Country: 'Canada', postal: 'T4B3K8' },
        { label: 'Athabasca University', value: 5, city: 'Athabasca', province: 'Alberta', Country: 'Canada', postal: 'T9S3A3' },
        { label: 'Banff Centre for Arts and Creativity', value: 6, city: 'Banff', province: 'Alberta', Country: 'Canada', postal: 'T1L1H5' },
        { label: 'Timberline Canadian Alpine Academy', value: 302328, city: 'Banff', province: 'Unknown', Country: 'Unknown', postal: 'T1L1H5' },
        { label: 'Academy of Learning - Brooks - Inactive', value: 300217, city: 'Brooks', province: 'Alberta', Country: 'Canada', postal: 'T1R0N8' },
        { label: 'Academy of Learning - Brooks', value: 301989, city: 'Brooks', province: 'Alberta', Country: 'Canada', postal: 'T1R0N8' },
        { label: 'Cypress College - Brooks', value: 300367, city: 'Brooks', province: 'Alberta', Country: 'Canada', postal: 'T1R1C4' },
        { label: 'ABES (Alberta Business and Educational Services) - Calgary', value: 128074, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2E6J5' },
        { label: 'ABM College', value: 250281, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T1Y6B6' },
        { label: 'Access International College', value: 10523, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3E7K1' },
        { label: 'Acts Leadership Training Centre - Calgary', value: 10437, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3A2G8' },
        { label: 'Aesthetics Pro', value: 301982, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2S0J2' },
        { label: 'Alberta Bible College - Calgary', value: 10329, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2K3J6' },
        { label: 'Alberta College of Acupuncture & Traditional Chinese Medicine', value: 8389, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2M1H5' },
        { label: 'Alberta College of Art and Design', value: 4, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2N4R3' },
        { label: 'Alberta College of Massage Therapy - Calgary', value: 128095, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2N1X7' },
        { label: 'Alberta Health and Safety Training Institute - Calgary', value: 239872, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T1Y7E5' },
        { label: 'Ambrose University', value: 10340, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3H0L5' },
        { label: 'APRA The Academy of Production & Recording Arts', value: 302036, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2G0Y7' },
        { label: 'Artists Within Makeup Academy', value: 9089, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2R0E5' },
        { label: 'Aveda Institute Calgary', value: 239954, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P1B7' },
        { label: 'Bow Valley College', value: 41, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2G4S6' },
        { label: 'Bredin Centre for Learning - Calgary', value: 241084, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P3N8' },
        { label: 'Bredin College of Business and Health Care - Calgary', value: 301532, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P3T4' },
        { label: 'Calgary College of Traditional Chinese Medicine and Acupuncture', value: 9299, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2G2R7' },
        { label: 'Calgary Dental Technology College', value: 9326, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3C0J5' },
        { label: 'Calgary Flying Club', value: 6099, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3Z3S4' },
        { label: 'Cambrooks College -  Downtown Campus', value: 304626, city: 'Calgary', province: 'Unknown', Country: 'Unknown', postal: 'T2P1B2' },
        { label: 'Cambrooks College', value: 300099, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2A0S8' },
        { label: 'Canadian Institute of Traditional Chinese Medicine', value: 9323, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2E1L6' },
        { label: 'Canadian School of Natural Nutrition - Calgary', value: 8485, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2A2P6' },
        { label: 'Canadian Theological Seminary - Calgary', value: 10339, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P3T5' },
        { label: 'CDI College of Business, Technology and Health Care - Calgary City Centre', value: 128774, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P3T6' },
        { label: 'CDI College of Business, Technology and Health Care - Calgary North', value: 128775, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2A1X5' },
        { label: 'CDI College of Business, Technology and Health Care - Calgary South', value: 248154, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2X1N4' },
        { label: 'CLI College of Business Health & Technology - Calgary', value: 301738, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2A5H5' },
        { label: 'Columbia College', value: 6173, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2E7N8' },
        { label: 'DelMar College', value: 241223, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2H0G4' },
        { label: 'DeVry Institute of Technology', value: 6184, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P3R7' },
        { label: 'DeVry University - Arizona', value: 11404, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2A7W4' },
        { label: 'Ecole Holt Couture School of Couture Sewing and Design', value: 300227, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2T0M4' },
        { label: 'Elevated Learning Academy Inc. - Calgary', value: 246374, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2G2R7' },
        { label: 'Ellevit Training Institute - Inactive', value: 244668, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2R0X8' },
        { label: 'Enform - Calgary', value: 236158, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2E8Y3' },
        { label: 'ERP Technicals Incorporation Inc.', value: 301481, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3J5H2' },
        { label: 'Evangel Bible College - Calgary', value: 10441, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2A7L8' },
        { label: 'Eveline Charles Academy - Calgary', value: 249218, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P4H9' },
        { label: 'Evergreen College - Calgary', value: 300577, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T1Y4T7' },
        { label: 'Evolve Dental Academy', value: 302053, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2T2C1' },
        { label: 'Flatline Response Inc.', value: 8681, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2C2V5' },
        { label: 'Foothills Med Ctr - Clinical Pastoral Educ', value: 10336, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2N2T9' },
        { label: 'Heritage College', value: 302014, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2K3L5' },
        { label: 'InnoTech College - Calgary', value: 301475, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2G2R7' },
        { label: 'Institute of Century Wellness', value: 300853, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2L1K8' },
        { label: 'KDM Dental College International Inc. - Calgary', value: 6284, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P3T1' },
        { label: 'Kinetic Medical Inc.', value: 301356, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2H2K1' },
        { label: 'LR Helicopters Inc.', value: 245368, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3Z3S4' },
        { label: 'M. Dent College', value: 304411, city: 'Calgary', province: 'Unknown', Country: 'Unknown', postal: 'T2S1V8' },
        { label: 'Makami College Inc. - Calgary', value: 300260, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2V4K8' },
        { label: 'MC College - Calgary', value: 6313, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P1A8' },
        { label: 'McBride Career Group Inc. - Calgary', value: 127865, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2R1J3' },
        { label: 'Medical Reception College 1 Ltd. - Calgary', value: 8786, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P3G2' },
        { label: 'MH Vicars School of Massage Therapy - Calgary', value: 128548, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3K5P3' },
        { label: 'Mount Royal University', value: 241078, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3E6K6' },
        { label: 'Mountain View Helicopters', value: 6088, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3Z3S6' },
        { label: 'MTG Healthcare Academy - Calgary', value: 253991, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3J3Z4' },
        { label: 'National Coaching Institute - Calgary', value: 6360, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2N1N4' },
        { label: 'National Institute of Wellness & Esthetics Inc.', value: 300120, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T1Y 5L3' },
        { label: 'Numa International Institute of Makeup and Design - Inactive', value: 243995, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2H0G6' },
        { label: 'Numa International Institute of Makeup and Design', value: 300917, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2H0G6' },
        { label: 'One Beauty Academy - Calgary', value: 301022, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2H0G6' },
        { label: 'Professional Institute of Massage Therapy', value: 9055, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3R0P3' },
        { label: 'Reeves College - Calgary City Centre', value: 9244, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2P3N8' },
        { label: 'Reeves College - Calgary North', value: 128263, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2E6Z3' },
        { label: 'Robertson College - Calgary NW', value: 9026, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2N2A1' },
        { label: 'Robertson College - Calgary SE', value: 300562, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2N2A1' },
        { label: 'Rocky Mountain College - Calgary', value: 10334, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2L1L1' },
        { label: 'Rosewood College', value: 300473, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3J0S4' },
        { label: 'School of Alberta Ballet - Calgary', value: 127932, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2R1K7' },
        { label: 'Southern Alberta Institute of Technology', value: 35, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2M0L4' },
        { label: 'Springbank Aero Flight Training Inc.', value: 12031, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3Z3S5' },
        { label: 'Springbank Air Training College Ltd.', value: 8754, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3Z3S4' },
        { label: 'St. Mary\'s University', value: 7606, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2X1Z4' },
        { label: 'Sundance College', value: 302130, city: 'Calgary', province: 'Unknown', Country: 'Unknown', postal: 'T2A6J9' },
        { label: 'The Esthetic Institute Training Center', value: 302039, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2H0J1' },
        { label: 'TOC Hair Studio & Akademy', value: 300570, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2H0K1' },
        { label: 'University of Calgary', value: 38, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2N1N4' },
        { label: 'Victorian Order of Nurses for Canada - Western Region - Inactive', value: 128512, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T3E4M2' },
        { label: 'Victory Bible College - Calgary', value: 10335, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2N4T6' },
        { label: 'Zeneba Academy of Esthetics - Inactive', value: 128527, city: 'Calgary', province: 'Alberta', Country: 'Canada', postal: 'T2G1Y4' },
        { label: 'Business IQ Training', value: 301502, city: 'Camrose', province: 'Alberta', Country: 'Canada', postal: 'T4V1R3' },
        { label: 'Canadian Lutheran Bible Institute - Camrose', value: 10331, city: 'Camrose', province: 'Alberta', Country: 'Canada', postal: 'T4V1W5' },
        { label: 'High Velocity Equipment Training College', value: 128842, city: 'Camrose', province: 'Alberta', Country: 'Canada', postal: 'T4V1R3' },
        { label: 'Embody School of Pilates', value: 301527, city: 'Canmore', province: 'Alberta', Country: 'Canada', postal: 'T1W2B7' },
        { label: 'Spa Works Esthetic and Spa Therapy Training', value: 300441, city: 'Canmore', province: 'Alberta', Country: 'Canada', postal: 'T1W1N4' },
        { label: 'Training Inc. - Cardston', value: 300944, city: 'Cardston', province: 'Alberta', Country: 'Canada', postal: 'T0K0K0' },
        { label: 'Clearwater College - Caroline', value: 10326, city: 'Caroline', province: 'Alberta', Country: 'Canada', postal: 'T0M0M0' },
        { label: 'Advance Institute of Wellness & Esthetics', value: 301507, city: 'Chestermere', province: 'Alberta', Country: 'Canada', postal: 'T1X1M1' },
        { label: 'Canadian Southern Baptist Seminary - Cochrane', value: 10332, city: 'Cochrane', province: 'Alberta', Country: 'Canada', postal: 'T4C2G1' },
        { label: 'Northern Institute of Massage Therapy Inc. - Cold Lake', value: 301660, city: 'Cold Lake', province: 'Alberta', Country: 'Canada', postal: 'T9M1P1' },
        { label: 'Total Health School of Nutrition', value: 9053, city: 'Condor', province: 'Alberta', Country: 'Canada', postal: 'T0M0P0' },
        { label: 'Calgary Flight Training Centre', value: 301277, city: 'Didsbury', province: 'Alberta', Country: 'Canada', postal: 'T0M0W0' },
        { label: 'Hope College', value: 300058, city: 'Drumheller', province: 'Alberta', Country: 'Canada', postal: 'T0J0Y0' },
        { label: 'MAX Campus', value: 239479, city: 'Drumheller', province: 'Alberta', Country: 'Canada', postal: 'T0J0Y0' },
        { label: 'A-1 Medical Training', value: 301097, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5G3A1' },
        { label: 'Academy of Learning - Calgary NE', value: 128751, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0N3' },
        { label: 'Academy of Learning - Calgary South', value: 128752, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0N3' },
        { label: 'Academy of Learning - Edmonton Downtown', value: 6007, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0N3' },
        { label: 'Academy of Learning - Edmonton South', value: 6012, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0N3' },
        { label: 'Academy of Learning - Edmonton West', value: 6023, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0N3' },
        { label: 'Academy of Learning - Medicine Hat', value: 9304, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0N3' },
        { label: 'Academy of Learning - Red Deer', value: 9048, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0N3' },
        { label: 'Alberta Academy of Aesthetics', value: 13009, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5T3J7' },
        { label: 'Alberta Caregiving Institute - Edmonton General Hospital', value: 241411, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6E5X5' },
        { label: 'Alberta College of Massage Therapy - Edmonton', value: 9252, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6R0T4' },
        { label: 'Alberta College of Massage Therapy - Fort McMurray', value: 9012, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6R0T4' },
        { label: 'Alberta College of Massage Therapy - Grande Prairie', value: 8148, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6R0T4' },
        { label: 'Alberta College of Massage Therapy - Lloydminster', value: 128096, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6R0T4' },
        { label: 'Alberta College of Massage Therapy - Red Deer', value: 301998, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6R0T4' },
        { label: 'Alberta Pipe Trades College - Edmonton', value: 301428, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5V1C8' },
        { label: 'Alberta School of Radiation Therapy', value: 6902, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J3N4' },
        { label: 'Archways Healing College', value: 302186, city: 'Edmonton', province: 'Unknown', Country: 'Unknown', postal: 'T5R5W5' },
        { label: 'Auctioneering College of Canada', value: 6074, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5M1V9' },
        { label: 'Bethesda Bible College - Edmonton', value: 10442, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5E0Y1' },
        { label: 'Bredin Centre for Learning - Edmonton', value: 8940, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5K2M5' },
        { label: 'Bredin College of Business and Health Care - Edmonton', value: 301535, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5K2M5' },
        { label: 'Campbell College Ltd.', value: 7001, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5G0X5' },
        { label: 'Canadian College of Massage & Wellness', value: 242713, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6M1G9' },
        { label: 'Canadian School of Natural Nutrition - Edmonton', value: 253300, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6E5J3' },
        { label: 'CDI College of Business, Technology and Health Care - Edmonton City Centre', value: 128776, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J 1R3' },
        { label: 'CDI College of Business, Technology and Health Care - Edmonton North', value: 128777, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5E6C2' },
        { label: 'CDI College of Business, Technology and Health Care - Edmonton South', value: 239648, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6B3R6' },
        { label: 'CDI College of Business, Technology and Health Care - Edmonton West', value: 248155, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5P4B3' },
        { label: 'CLAC Career Development College Inc.', value: 304545, city: 'Edmonton', province: 'Unknown', Country: 'Unknown', postal: 'T5V1B8' },
        { label: 'CLI College of Business, Health and Technology - Edmonton North', value: 300672, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5B0T1' },
        { label: 'CLI College of Business, Health and Technology - Edmonton', value: 256161, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5H3J6' },
        { label: 'Concordia Lutheran Seminary - Edmonton', value: 10328, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5B4E3' },
        { label: 'Concordia University of Edmonton', value: 7, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5B4E4' },
        { label: 'Cosmopolitan Make-up Artist College', value: 244900, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J1M4' },
        { label: 'Digital School', value: 8942, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0N3' },
        { label: 'Edmonton Digital Arts College', value: 8767, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J1B9' },
        { label: 'Edmonton Flying Club', value: 6197, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5Z3P3' },
        { label: 'Edmonton School of Ballet - EDMONTON', value: 12867, city: 'EDMONTON', province: 'Alberta', Country: 'Canada', postal: 'T6C1N8' },
        { label: 'Elevated Learning Academy Inc. - Edmonton', value: 254004, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J1V9' },
        { label: 'Est-elle Academy of Hair Design Ltd.', value: 6205, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6E1V1' },
        { label: 'European Institute of Esthetics', value: 8938, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6E6T9' },
        { label: 'Eveline Charles Academy - Edmonton', value: 13161, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J4H5' },
        { label: 'Grant MacEwan University', value: 241075, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J2P2' },
        { label: 'GRB College of Welding', value: 6247, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6E0A9' },
        { label: 'H & B Massage Therapy Training Centre', value: 239056, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5P4Y1' },
        { label: 'InnoTech College - Edmonton', value: 301832, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J1V9' },
        { label: 'Inspection Time Training Career College - Calgary', value: 301339, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5S1A2' },
        { label: 'Inspection Time Training Career College - Edmonton', value: 302220, city: 'Edmonton', province: 'Unknown', Country: 'Unknown', postal: 'T5S1A2' },
        { label: 'KDM Dental College International Inc. - Edmonton', value: 6287, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0H8' },
        { label: 'King\'s University, The', value: 22, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6B2H3' },
        { label: 'MaKami College  Inc. - Edmonton', value: 8551, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6A1G3' },
        { label: 'MC College - Edmonton', value: 6315, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J1G1' },
        { label: 'McBride Career Group Inc. - Edmonton', value: 127866, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5K2M5' },
        { label: 'Medical Reception College 1 Ltd. - Edmonton', value: 8985, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J3S4' },
        { label: 'MH Vicars School of Massage Therapy - Edmonton', value: 8607, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6J6V7' },
        { label: 'Mount Carmel Bible School - Edmonton', value: 301210, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6A1E7' },
        { label: 'MTG Healthcare Academy - Edmonton', value: 301708, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T2E8S1' },
        { label: 'Newman Theological College - Edmonton', value: 30, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6A0B2' },
        { label: 'Nightingale Academy of Health Services Inc.', value: 8496, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5E4K3' },
        { label: 'NorQuest College', value: 42, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J1L6' },
        { label: 'Northern Alberta Institute of Technology', value: 27, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5G2R1' },
        { label: 'Painter Decorator College', value: 302333, city: 'Edmonton', province: 'Unknown', Country: 'Unknown', postal: 'T6E6T7' },
        { label: 'Pastorial Institute of Edmonton - Edmonton', value: 10439, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5H1E7' },
        { label: 'Pixel Blue College', value: 128795, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J1V9' },
        { label: 'Powersound Recording Studios', value: 253305, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5H3K6' },
        { label: 'Reeves College - Edmonton', value: 9054, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J1R3' },
        { label: 'Robertson College - Edmonton', value: 255122, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J3M5' },
        { label: 'Slate Training Centre - Inactive', value: 12982, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5M3L7' },
        { label: 'Solomon College', value: 248080, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5J0B3' },
        { label: 'South Edmonton School of Massage Therapy', value: 253387, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6L6K3' },
        { label: 'St. Stephen\'s College - Edmonton', value: 10325, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6G2J6' },
        { label: 'Taylor College and Seminary - Edmonton', value: 238370, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6J4T3' },
        { label: 'Temple Bible College - Edmonton', value: 10438, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6K3R9' },
        { label: 'The Excel Academy', value: 8031, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5H4R2' },
        { label: 'TLC Edmonton: Training for Foreign Caregivers', value: 9314, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5P1X9' },
        { label: 'University of Alberta', value: 37, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6G2M7' },
        { label: 'Vanguard College - Edmonton', value: 10330, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5G2J9' },
        { label: 'Wholistic Health Training & Research Centre', value: 248056, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T6B3J4' },
        { label: 'Yellowhead Tribal College - Edmonton', value: 8404, city: 'EDMONTON', province: 'Alberta', Country: 'Canada', postal: 'T5S1G4' },
        { label: 'Yellowhead Tribal College Edmonton - AB', value: 302064, city: 'Edmonton', province: 'Alberta', Country: 'Canada', postal: 'T5S1G4' },
        { label: 'Global College of Auctioneering Ltd.', value: 302157, city: 'Foothills', province: 'Unknown', Country: 'Unknown', postal: 'T1V1M3' },
        { label: 'Keyano College', value: 21, city: 'Fort McMurray', province: 'Alberta', Country: 'Canada', postal: 'T9H2H7' },
        { label: 'McMurray Aviation - Fort McMurray', value: 6336, city: 'Fort McMurray', province: 'Alberta', Country: 'Canada', postal: 'T9H5B4' },
        { label: 'AccData Computer Systems & Training', value: 301778, city: 'Grande Prairie', province: 'Alberta', Country: 'Canada', postal: 'T8V0T8' },
        { label: 'Grande Prairie Regional College', value: 14, city: 'Grande Prairie', province: 'Alberta', Country: 'Canada', postal: 'T8V4C4' },
        { label: 'Mar-Don Academy of Hair Design', value: 244187, city: 'Grande Prairie', province: 'Alberta', Country: 'Canada', postal: 'T8V0X9' },
        { label: 'Mayfair Business College', value: 6327, city: 'Grande Prairie', province: 'Alberta', Country: 'Canada', postal: 'T8V0T8' },
        { label: 'Northern Lights Academy of Cosmetology Ltd. - Inactive', value: 128311, city: 'Grande Prairie', province: 'Alberta', Country: 'Canada', postal: 'T8V1V5' },
        { label: 'One Beauty Academy - Grande Prairie', value: 300836, city: 'Grande Prairie', province: 'Alberta', Country: 'Canada', postal: 'T8V0X9' },
        { label: 'Start - Rite Driver Education Ltd.', value: 7735, city: 'Grande Prairie', province: 'Alberta', Country: 'Canada', postal: 'T8V6A4' },
        { label: 'Northern Lakes College', value: 43, city: 'Grouard', province: 'Alberta', Country: 'Canada', postal: 'T0G1C0' },
        { label: 'Academy of Learning - High River', value: 236253, city: 'High River', province: 'Alberta', Country: 'Canada', postal: 'T1V1T2' },
        { label: 'Maskwacis Cultural College - Hobbema', value: 6322, city: 'Hobbema', province: 'Alberta', Country: 'Canada', postal: 'T0C1N0' },
        { label: 'Interior Heavy Equipment Operator School Inc.', value: 244901, city: 'Innisfail', province: 'Alberta', Country: 'Canada', postal: 'T0M1R0' },
        { label: 'Interior Heavy Equipment Operator School', value: 301620, city: 'Innisfail', province: 'Alberta', Country: 'Canada', postal: 'T4G1T8' },
        { label: 'Portage College', value: 40, city: 'Lac La Biche', province: 'Alberta', Country: 'Canada', postal: 'T0A2C0' },
        { label: 'Burman University', value: 9, city: 'Lacombe', province: 'Alberta', Country: 'Canada', postal: 'T4L2E5' },
        { label: 'Lacombe Municipal Ambulance Service Association - Inactive', value: 9405, city: 'Lacombe', province: 'Alberta', Country: 'Canada', postal: 'T4L0B6' },
        { label: 'Canadian Avalanche Association', value: 6120, city: 'Lake Louise', province: 'Alberta', Country: 'Canada', postal: 'T0L1E0' },
        { label: 'Alberta School of Dog Grooming', value: 249818, city: 'Leduc', province: 'Alberta', Country: 'Canada', postal: 'T9E6V9' },
        { label: 'Bella Elite Beauty & Barber Academy Ltd.', value: 301123, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1J2J5' },
        { label: 'Excel Flight Training Incorporated', value: 8730, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1K7N3' },
        { label: 'L.A. School of Hair Design (1989) Ltd.', value: 6290, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1J2J5' },
        { label: 'Lethbridge College', value: 23, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1K1L6' },
        { label: 'Purely Inspired Academy of Beauty', value: 128515, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1J0E5' },
        { label: 'Reeves College - Lethbridge', value: 128568, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1J2B6' },
        { label: 'Royal Health Care Aide Training School - Lethbridge', value: 246877, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1J2B9' },
        { label: 'Southern Alberta Institute of Massage', value: 9546, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1J3E7' },
        { label: 'Training Inc. - Lethbridge', value: 6455, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1J0T5' },
        { label: 'University of Lethbridge', value: 39, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1K3M4' },
        { label: 'Victory Bible College - Lethbridge', value: 10440, city: 'Lethbridge', province: 'Alberta', Country: 'Canada', postal: 'T1J4K4' },
        { label: '3A Academy & Consulting Ltd.', value: 9566, city: 'Lloydminster', province: 'Alberta', Country: 'Canada', postal: 'T9V0C5' },
        { label: 'Reeves College - Lloydminster', value: 9019, city: 'Lloydminster', province: 'Alberta', Country: 'Canada', postal: 'T9V2A1' },
        { label: 'Connections Career & Safety Services - Medicine Hat', value: 128504, city: 'Medicine Hat', province: 'Alberta', Country: 'Canada', postal: 'T1A1X8' },
        { label: 'Cypress College - Legion Campus', value: 302097, city: 'Medicine Hat', province: 'Unknown', Country: 'Unknown', postal: 'T1A0E1' },
        { label: 'Cypress College - Medicine Hat', value: 128133, city: 'Medicine Hat', province: 'Alberta', Country: 'Canada', postal: 'T1A1J2' },
        { label: 'Cypress College - Taber', value: 254896, city: 'Medicine Hat', province: 'Alberta', Country: 'Canada', postal: 'T1A1J2' },
        { label: 'Masters School of Hair Design', value: 6325, city: 'Medicine Hat', province: 'Alberta', Country: 'Canada', postal: 'T1A0C9' },
        { label: 'Medicine Hat College', value: 25, city: 'Medicine Hat', province: 'Alberta', Country: 'Canada', postal: 'T1A3Y6' },
        { label: 'One Beauty Academy - Medicine Hat', value: 300422, city: 'Medicine Hat', province: 'Alberta', Country: 'Canada', postal: 'T1A0C9' },
        { label: 'Super T Aviation Academy', value: 129190, city: 'Medicine Hat', province: 'Alberta', Country: 'Canada', postal: 'T1A5G4' },
        { label: 'Enform - NISKU', value: 13010, city: 'NISKU', province: 'Alberta', Country: 'Canada', postal: 'T9E7Z6' },
        { label: 'Olds College', value: 32, city: 'Olds', province: 'Alberta', Country: 'Canada', postal: 'T4H1R6' },
        { label: 'E-Z Air Helicopter Training Inc.', value: 6188, city: 'Parkland County', province: 'Alberta', Country: 'Canada', postal: 'T7X3L7' },
        { label: 'Sky Wings Aviation Academy', value: 6434, city: 'Penhold', province: 'Alberta', Country: 'Canada', postal: 'T0M1R0' },
        { label: 'Training Inc. - Pincher Creek', value: 300947, city: 'Pincher Creek', province: 'Alberta', Country: 'Canada', postal: 'T0K1W0' },
        { label: 'Academic Express Adult Education & Training', value: 301518, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N1X7' },
        { label: 'Academic Express Adult Education and Training', value: 300906, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N1X7' },
        { label: 'Academy of Professional Hair Design', value: 9319, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N1V1' },
        { label: 'Alberta Health and Safety Training Institute - Red Deer', value: 301128, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4P3Z5' },
        { label: 'Alberta Institute of Massage', value: 6049, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4P2A5' },
        { label: 'Bredin College of Business and Health Care - Red Deer', value: 302348, city: 'Red Deer', province: 'Unknown', Country: 'Unknown', postal: 'T4N6H2' },
        { label: 'CDI College of Business, Technology and Health Care - Red Deer', value: 304498, city: 'Red Deer', province: 'Unknown', Country: 'Unknown', postal: 'T4N6C2' },
        { label: 'Home Church Bible College - Red Deer', value: 301434, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N5E4' },
        { label: 'MC College - Red Deer', value: 6318, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N1Y3' },
        { label: 'McBride Career Group Inc. - Red Deer', value: 301131, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N3T1' },
        { label: 'Medi Aesthetics Institute of Canada', value: 238284, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N2C8' },
        { label: 'MTG Healthcare Academy - Red Deer', value: 301031, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N1S6' },
        { label: 'National Manual Osteopathic College', value: 300296, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N4H3' },
        { label: 'Northern Institute of Massage Therapy Inc. - Red Deer', value: 9541, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N4H3' },
        { label: 'Red Deer College', value: 34, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N5H5' },
        { label: 'Sultana\'s Beauty Clinic and School', value: 6439, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4R1L3' },
        { label: 'The Health Care Aide Academy', value: 252470, city: 'Red Deer', province: 'Alberta', Country: 'Canada', postal: 'T4N1V1' },
        { label: 'Rosebud School of The Arts - Rosebud', value: 10333, city: 'Rosebud', province: 'Alberta', Country: 'Canada', postal: 'T0J2T0' },
        { label: 'Peace River Bible Institute - Sexsmith', value: 10324, city: 'Sexsmith', province: 'Alberta', Country: 'Canada', postal: 'T0H3C0' },
        { label: 'Academy of Reflexology and Massage', value: 302092, city: 'Sherwood Park', province: 'Unknown', Country: 'Unknown', postal: 'T8A1E6' },
        { label: 'Cooking Lake Aviation Services', value: 300958, city: 'Sherwood Park', province: 'Alberta', Country: 'Canada', postal: 'T8E1H1' },
        { label: 'Emergency Services Academy', value: 129129, city: 'Sherwood Park', province: 'Alberta', Country: 'Canada', postal: 'T8A2A8' },
        { label: 'International Academy of Esthetics', value: 6273, city: 'Sherwood Park', province: 'Alberta', Country: 'Canada', postal: 'T8A6A2' },
        { label: 'Medi Aesthetics Institute of Canada - Sherwood Park', value: 300156, city: 'Sherwood Park', province: 'Alberta', Country: 'Canada', postal: 'T8H 0M2' },
        { label: 'The Fur Institute - Inactive', value: 128783, city: 'Sherwood Park', province: 'Alberta', Country: 'Canada', postal: 'T8A4C7' },
        { label: 'Bredin College of Business and Health Care - Spruce Grove', value: 129175, city: 'Spruce Grove', province: 'Alberta', Country: 'Canada', postal: 'T7X2Z8' },
        { label: 'Synergy Flight Training Inc. - Spruce Grove', value: 301711, city: 'Spruce Grove', province: 'Alberta', Country: 'Canada', postal: 'T7X3L7' },
        { label: 'Professional Medical Associates - Calgary', value: 8447, city: 'St Albert', province: 'Alberta', Country: 'Canada', postal: 'T8n4J9' },
        { label: 'Nechi Institute Centre of Indigenous Learning - ST. ALBERT', value: 12968, city: 'ST. ALBERT', province: 'Alberta', Country: 'Canada', postal: 'T8N2G3' },
        { label: 'Professional Medical Associates - St. Albert', value: 7924, city: 'St. Albert', province: 'Alberta', Country: 'Canada', postal: 'T8N4J9' },
        { label: 'University nuhelot\'ine thaiyots\'ii nistameyimakanak Blue Quills', value: 6090, city: 'St. Paul', province: 'Alberta', Country: 'Canada', postal: 'T0A3A0' },
        { label: 'Covenant Bible College - Strathmore', value: 10337, city: 'Strathmore', province: 'Alberta', Country: 'Canada', postal: 'T1P1H8' },
        { label: 'Centennial Flight Centre Inc.', value: 9122, city: 'Sturgeon County', province: 'Alberta', Country: 'Canada', postal: 'T8T0E3' },
        { label: 'Namao Flying Club', value: 6357, city: 'Sturgeon County', province: 'Alberta', Country: 'Canada', postal: 'T8T0E3' },
        { label: 'Synergy Flight Training Inc. - Sturgeon County', value: 302278, city: 'Sturgeon County', province: 'Alberta', Country: 'Canada', postal: 'T8T0E3' },
        { label: 'Prairie Bible Institute - Three Hills', value: 10323, city: 'Three Hills', province: 'Alberta', Country: 'Canada', postal: 'T0M2N0' },
        { label: 'Prairie School of Mission Aviation', value: 7583, city: 'Three Hills', province: 'Alberta', Country: 'Canada', postal: 'T0M2N0' },
        { label: 'Professional Medical Associates - Three Hills', value: 241599, city: 'Three Hills', province: 'Alberta', Country: 'Canada', postal: 'T0M2N0' },
        { label: 'Maskwacis Cultural College - Sturgeon Lake', value: 8381, city: 'Valleyview', province: 'Alberta', Country: 'Canada', postal: 'T0H3N0' },
        { label: 'Lakeland College', value: 24, city: 'Vermilion', province: 'Alberta', Country: 'Canada', postal: 'T9X1K5' },
        { label: 'Absolute Aviation', value: 238429, city: 'Wetaskiwin', province: 'Alberta', Country: 'Canada', postal: 'T9A3S1' },
        { label: 'Rotorworks Inc.', value: 8803, city: 'Whitecourt', province: 'Alberta', Country: 'Canada', postal: 'T7S1N3' },
    ];

    getAll(): Observable<any[]> {
        return of(this.institutions);
    }

    getbyValue(value: number): Observable<any> {
        const item = this.institutions.find(
            function (obj) { return obj.value === value; }
        );
        return of(item);
    }

}
